name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! | Be sure to read the [wiki first](https://github.com/IsenBot/IsenBot-MongoDB/wiki)

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How do we see the problem?

  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: If possible please provide textual output instead of screenshots.
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      value : "- OS : [e.g. iOS]\n- nodejs [e.g. 19.1.0]\n- discord.js [e.g. 14.7.1]\n"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.