name: IsenBot Action

on:
  push:
    paths-ignore:
      - 'package.json'
      - '.gitignore'
      - '.github/**'
      - '**.md'

permissions:
  contents: write
  deployments: write
  packages: write
  pull-requests: write

jobs:
  version_job:
    runs-on: ubuntu-latest
    name: Package version auto-increment job
    strategy:
      matrix:
        node-version: [16.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --only=dev
      - name: Determine commit type
        id: get_type
        uses: ./.github/actions/get_commit_type/
        with:
          commit-message: ${{ github.event.commits[0].message }}
      - name: Increment version
        uses: ./.github/actions/update_version/
        with:
          type: ${{ steps.get_type.outputs.type }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
