name: IsenBot Action

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - '.gitignore'
      - '.github/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - '.gitignore'
      - '.github/**'
      - '**.md'  

permissions:
  contents: write
  deployments: write
  packages: write
  pull-requests: write

jobs:
  version_job:
    runs-on: ubuntu-latest
    name: Package version auto-increment job
    strategy:
      matrix:
        node-version: [16.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --only=dev
      - name: Determine all commit types
        id: get_types
        uses: ./.github/actions/get_commits_types/
        with:
          first-commit: ${{ github.event.before }}
          last-commit: ${{ github.event.after }}
      - name: Increment version
        uses: ./.github/actions/update_version/
        with:
          types: ${{ steps.get_types.outputs.types }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
